# deepseek_r1_distill_qwen_7b-megatron_lm-dp_2-tp_4-pp_2-perlmutter-group_1.yaml
version: 1

description: >
  DeepSeek-Qwen2-7B (Distill) training profile on 16 NVIDIA A100 GPUs across 4 nodes. 
  Configured with hybrid 3D parallelism: 4-way Tensor Parallelism (TP=4) to match 
  node boundaries, 2-way Pipeline Parallelism (PP=2), and 2-way Data Parallelism (DP=2). 
  Features a sequence length of 4096 and a large 151k vocabulary.

hf_url: https://huggingface.co/deepseek-ai/DeepSeek-R1-Distill-Qwen-7B
trace_url: https://drive.google.com/file/d/14Z906ZsuVgKD4Z4o9cSNVoKdppTmSZ0s/view?usp=drive_link
workload:
  model:
    phase: training
    moe: false
    granularity: model_fwd_bwd_pass
    model_family: deepseek-qwen2-7b
    precision: bf16
    epochs: 1
    iteration: 40
  data:
    batch_size: 2
    seq_len: 4096
    dataset: wikitext
  hardware:
    network_topo:
      topology: slingshot
      bandwidth_gbps:
        - 200
        - 2000
    xpu_spec:
      type: GPU
      model: nvidia_a100
      total_count: 16
      count_per_node: 4
    driver_version: cuda_12.4

Model-executor:
  framework: 
    name: megatron-lm
    compiler_tool_selection: plain_pytorch
  model_plan_parallelization:
    dp_replicate: 2
    dp_shard: 1
    tp: 4
    pp: 2
    cp: 1
  communication_library:
    name: NCCL
    version: 2.21.0
    env:
      NCCL_DEBUG: INFO
      CUDA_DEVICE_MAX_CONNECTIONS: 1
  protocol_selection:
    - rocev2
    - p2p

metric_source:
  traces:
    - kineto_trace
  metrics_specific_trace:
    - memory_trace